### ISSUE TITLE
More info on components in relation to this repo

### ISSUE THREAD

**Issue by mhulse** [jaydenseric/Fix#2]
Hello,

I really like the direction of this code, but [on your site](http://jaydenseric.com/blog/forget-normalize-or-resets-lay-your-own-css-foundation), I read:

> Boy do things move fast! Global CSS is now an anti-pattern with components emerging as a best practice.

I'm just curious if you have links to the article (or articles) that motivated you to put that message at the top of your page?

Thanks!

**Comment by jaydenseric** [comment]
Hi!

Componentization is a realy hot topic and is the future of web development. It involves developing libraries of small, reusable UI components to construct our views in a modular fashion. The code that defines each component (HTML, JS, CSS, etc.) never pollutes the global scope and is self contained in a folder. Components import and use other components as children by setting their properties (props in jargon). You know you have done well if you can easily copy components such as slideshows, inputs or buttons between projects and just start using them.

Componentization solves 90% of front end headaches – a bold claim I can justify over a lengthy blog post some time. It fits the agile process really well and has done miracles for our team. The React community in particular is driving a lot of the innovation and thought leadership. We don't use React that much in our agency; it is important to note that as an approach it transcends languages, libraries or frameworks. Some technologies are play nicer than others though. ES6 modules are fantastic. CSS however, by nature, pollutes the global scope and cascades down through every descendant.

If one person sets `h1 { color: red }` anywhere in your codebase it can recursively effect every primary heading and ruin your existing designs. If that remains in your project, the next time you add a new component with a `h1` you will have needs to account for the existing styles. I have seen stylesheets for relatively small websites grow to 20,000+ lines over a 2-3 years due to incomprehensible cascading and overriding. Tracing element styles in the inspector will give you PTSD.

There is a lot you can do with ordinary CSS class naming, imports and file structure to componentize. See [Barebones](https://github.com/jaydenseric/Barebones) for an example that uses webpack to generate an single optimized CSS bundle file for your componentized project. The problem with a discipline based approach is that it can be easily derailed by code vandals. Read this excelent intro to [CSS Modules](http://glenmaddern.com/articles/css-modules), a less fragile approach that I use for React projects.

The likely future of styling is to drop CSS stylesheets, along with the growing list of required tooling (PostCSS, stylelint, etc.) in favour of a JS approach such as [Radium](http://stack.formidable.com/radium). I plan to try this out in practice as soon as I can.

Strangely despite such a strong recent rejection of global CSS by the developer community, normalize/reset stylesheets for some reason are given a free pass and are taken for granted. Having so far shipped at least 20 production sites with no global styles whatsoever, I see a lot of parallels with jQuery. Developers assume they can't live without it, it's all they know so they stick with it. I really believe in this new approach, and so far have come not where near where I want to be with the sharing and evangelizing. Keep an eye on the [next branch](https://github.com/jaydenseric/Fix/tree/next).

**Comment by mhulse** [comment]
Wow, awesome info! So much to research and think about!!! :)

Thanks so much @jaydenseric, I really appreciate your awesome feedback and help!

I'm really looking forward to seeing how this project evolves.

Watching things now. 👍 :octocat:
