### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by breadadams** [jaydenseric/Fix#4]
Hey, are there any plans to get Fix on `npm`?

**Comment by jaydenseric** [comment]
In short, no 🙂 

You can find a detailed explanation in [this thread](https://github.com/jaydenseric/Fix/issues/3#issuecomment-271753077).

You are far better off not using global normalization or reset stylesheets, or any global styles for that matter. I should really add a deprecation notice to the readme. Note that a few of the fixes like `::-moz-focus-inner` have been fixed in browsers and are no longer relevant.
